trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
  - powershell: |
      # Install Terraform
      Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_windows_386.zip -OutFile terraform.zip
      Expand-Archive -Path terraform.zip -DestinationPath $Env:TEMP
      Move-Item -Path "$Env:TEMP\terraform.exe" -Destination "C:\terraform\terraform.exe"
      $env:Path += ";C:\terraform"
    displayName: 'Install Terraform'

  - powershell: terraform version
    displayName: 'Verify Terraform Installation'

  - powershell: terraform init
    displayName: 'Terraform Init'

  - powershell: terraform validate
    displayName: 'Terraform Validate'
